name: anydoor
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.08.22=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=23.3.1=py38h06a4308_0
  - python=3.8.5=h7579374_1
  - readline=8.2=h5eee18b_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py38h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - absl-py==2.0.0
    - aiofiles==23.2.1
    - aiohttp==3.9.1
    - aiosignal==1.3.1
    - albumentations==1.3.0
    - altair==5.2.0
    - annotated-types==0.6.0
    - antlr4-python3-runtime==4.8
    - anyio==3.7.1
    - async-timeout==4.0.3
    - attrs==23.1.0
    - cachetools==5.3.2
    - certifi==2023.11.17
    - charset-normalizer==3.3.2
    - click==8.1.7
    - cloudpickle==3.0.0
    - cmake==3.28.0
    - contourpy==1.1.1
    - cycler==0.12.1
    - cython==3.0.6
    - einops==0.3.0
    - exceptiongroup==1.2.0
    - fastapi==0.105.0
    - ffmpy==0.3.1
    - filelock==3.13.1
    - fonttools==4.46.0
    - frozenlist==1.4.0
    - fsspec==2023.12.2
    - ftfy==6.1.3
    - future==0.18.3
    - fvcore==0.1.5.post20221221
    - google-auth==2.25.2
    - google-auth-oauthlib==1.0.0
    - gradio==3.39.0
    - gradio-client==0.7.2
    - grpcio==1.60.0
    - h11==0.14.0
    - httpcore==1.0.2
    - httpx==0.25.2
    - huggingface-hub==0.19.4
    - idna==3.6
    - imageio==2.33.1
    - importlib-metadata==7.0.0
    - importlib-resources==6.1.1
    - iopath==0.1.10
    - jinja2==3.1.2
    - joblib==1.3.2
    - jsonschema==4.20.0
    - jsonschema-specifications==2023.11.2
    - kiwisolver==1.4.5
    - lazy-loader==0.3
    - linkify-it-py==2.0.2
    - lit==17.0.6
    - lvis==0.5.3
    - markdown==3.5.1
    - markdown-it-py==2.2.0
    - markupsafe==2.1.3
    - matplotlib==3.7.4
    - mdit-py-plugins==0.3.3
    - mdurl==0.1.2
    - mpmath==1.3.0
    - multidict==6.0.4
    - mypy-extensions==1.0.0
    - networkx==3.1
    - numpy==1.23.1
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - oauthlib==3.2.2
    - omegaconf==2.1.1
    - open-clip-torch==2.17.1
    - opencv-contrib-python==4.3.0.36
    - opencv-python==4.7.0.72
    - opencv-python-headless==4.7.0.72
    - orjson==3.9.10
    - packaging==23.2
    - pandas==2.0.3
    - pillow==9.4.0
    - pkgutil-resolve-name==1.3.10
    - portalocker==2.8.2
    - protobuf==3.20.3
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pycocotools==2.0.7
    - pydantic==2.5.2
    - pydantic-core==2.14.5
    - pydeprecate==0.3.1
    - pydub==0.25.1
    - pyparsing==3.1.1
    - pyre-extensions==0.0.23
    - python-dateutil==2.8.2
    - python-multipart==0.0.6
    - pytorch-lightning==1.5.0
    - pytz==2023.3.post1
    - pywavelets==1.4.1
    - pyyaml==6.0.1
    - qudida==0.0.4
    - referencing==0.32.0
    - regex==2023.10.3
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rpds-py==0.13.2
    - rsa==4.9
    - safetensors==0.2.7
    - scikit-image==0.21.0
    - scikit-learn==1.3.2
    - scipy==1.9.1
    - semantic-version==2.10.0
    - sentencepiece==0.1.99
    - setuptools==66.0.0
    - share==1.0.4
    - six==1.16.0
    - sniffio==1.3.0
    - starlette==0.27.0
    - submitit==1.5.1
    - sympy==1.12
    - tabulate==0.9.0
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.2
    - termcolor==2.4.0
    - threadpoolctl==3.2.0
    - tifffile==2023.7.10
    - timm==0.6.12
    - tokenizers==0.12.1
    - toolz==0.12.0
    - torch==2.0.0
    - torchmetrics==0.6.0
    - torchvision==0.15.1
    - tqdm==4.65.0
    - transformers==4.19.2
    - triton==2.0.0
    - typing-extensions==4.9.0
    - typing-inspect==0.9.0
    - tzdata==2023.3
    - uc-micro-py==1.0.2
    - urllib3==2.1.0
    - uvicorn==0.24.0.post1
    - wcwidth==0.2.12
    - websockets==11.0.3
    - werkzeug==3.0.1
    - xformers==0.0.18
    - yacs==0.1.8
    - yarl==1.9.4
    - zipp==3.17.0

